dcConsData = [
    { name: "쑥스럽.png", keywords: ["쑥스럽", "집요정쑥스럽"], tags: ["집요정"] },
    { name: "모름.png", keywords: ["모름", "모릅니다", "집요정모름", "집요정모릅니다"], tags: ["집요정"] },
    { name: "인증.png", keywords: ["인증", "인증함", "집요정인증", "집요정인증함"], tags: ["집요정"] },
    { name: "선물.png", keywords: ["선물", "선물이야", "집요정선물", "집요정선물이야"], tags: ["집요정"] },
    { name: "워워.png", keywords: ["워워", "집요정워워"], tags: ["집요정"] },
    { name: "아이구야.png", keywords: ["아이구야", "집요정아이구야"], tags: ["집요정"] },
    { name: "어흑.png", keywords: ["어흑", "어흑흑", "집요정어흑", "집요정어흑흑"], tags: ["집요정"] },
    { name: "O.png", keywords: ["O", "o", "집요정O", "집요정o"], tags: ["집요정"] },
    { name: "X.png", keywords: ["X", "x", "집요정X", "집요정x"], tags: ["집요정"] },
    { name: "돼.png", keywords: ["돼", "집요정돼"], tags: ["집요정"] },
    { name: "안돼.png", keywords: ["안돼", "집요정안돼"], tags: ["집요정"] },
    { name: "눈물.png", keywords: ["눈물", "집요정눈물"], tags: ["집요정"] },
    { name: "사망.png", keywords: ["사망", "집요정사망"], tags: ["집요정"] },
    { name: "당황끄덕.png", keywords: ["당황끄덕", "끄덕", "집요정당황끄덕", "집요정끄덕"], tags: ["집요정"] },
    { name: "두근두근.png", keywords: ["두근두근", "집요정두근두근"], tags: ["집요정"] },
    { name: "항복.png", keywords: ["항복", "집요정항복"], tags: ["집요정"] },
    { name: "하트.png", keywords: ["하트", "집요정하트"], tags: ["집요정"] },
    { name: "무시무시.png", keywords: ["무시무시", "집요정무시무시"], tags: ["집요정"] },
    { name: "아니다.png", keywords: ["아니다", "집요정아니다"], tags: ["집요정"] },
    { name: "팩트.png", keywords: ["팩트", "집요정팩트"], tags: ["집요정"] },
    { name: "고양이가.png", keywords: ["고양이가", "집요정고양이가"], tags: ["집요정"] },
    { name: "두근.png", keywords: ["두근", "집요정두근"], tags: ["집요정"] },
    { name: "죽창.png", keywords: ["죽창", "집요정죽창"], tags: ["집요정"] },
    { name: "인정.png", keywords: ["인정", "집요정인정"], tags: ["집요정"] },
    { name: "물음표.png", keywords: ["물음표", "?", "집요정물음표"], tags: ["집요정"] },
    { name: "우웩.png", keywords: ["우웩", "집요정우웩"], tags: ["집요정"] },
    { name: "어그래.png", keywords: ["어그래", "집요정어그래"], tags: ["집요정"] },
    { name: "조의.png", keywords: ["조의", "집요정조의"], tags: ["집요정"] },
    { name: "안녕2.png", keywords: ["안녕2", "집요정안녕"], tags: ["집요정"] },
    { name: "잘자.png", keywords: ["잘자", "집요정잘자"], tags: ["집요정"] },
    { name: "수근수근.png", keywords: ["수근수근", "집요정수근수근"], tags: ["집요정"] },
    { name: "조와.png", keywords: ["조와", "집요정조와"], tags: ["집요정"] },
	
	{name:"소닉링없찐.gif", 	keywords:["링없찐"], 							tags:["소닉", "소닉매니아"]},
	{name:"소닉결혼반지.png",	keywords:["결혼반지"],						tags:["소닉", "소닉매니아"]},
	{name:"주인님.png",				keywords:["주인님"],							tags:["자살"]},
	{name:"겉바속촉.gif",			keywords:["겉바속촉", "가로쉬"],	tags:["와우", "헬스크림"]},

	{name:"안녕.png", 	keywords:["안녕"], 							tags:["핑키빈콘"]},
	{name:"왜모름.png", 	keywords:["왜모름"], 							tags:["핑키빈콘"]},
	{name:"욵지.png", 	keywords:["욵지"], 							tags:["핑키빈콘"]},
	{name:"ㄴㄴ.png", 	keywords:["ㄴㄴ"], 							tags:["핑키빈콘"]},
	{name:"ㄹㅇ.png", 	keywords:["ㄹㅇ"], 							tags:["핑키빈콘"]},
	{name:"ㅁㄹ.png", 	keywords:["ㅁㄹ"], 							tags:["핑키빈콘"]},
	{name:"ㅂㄹ.png", 	keywords:["ㅂㄹ"], 							tags:["핑키빈콘"]},
	{name:"ㅇㅈ.png", 	keywords:["ㅇㅈ"], 							tags:["핑키빈콘"]},
	{name:"ㅋㅋ.png", 	keywords:["ㅋㅋ"], 							tags:["핑키빈콘"]},
	{name:"ㅗㅜㅑ.png", 	keywords:["ㅗㅜㅑ"], 							tags:["핑키빈콘"]},
	{name:"개추.png", 	keywords:["개추"], 							tags:["핑키빈콘"]},
	{name:"고고헛.png", 	keywords:["고고헛"], 							tags:["핑키빈콘"]},
	{name:"구웨엑.png", 	keywords:["구웨엑"], 							tags:["핑키빈콘"]},
	{name:"굿.png", 	keywords:["굿"], 							tags:["핑키빈콘"]},
	{name:"나만운없어.png", 	keywords:["나만운없어"], 							tags:["핑키빈콘"]},
    {name:"누렁.png", 	keywords:["누렁"], 							tags:["핑키빈콘"]},
	{name:"돈주머니.png", 	keywords:["돈주머니"], 							tags:["핑키빈콘"]},
	{name:"땀.png", 	keywords:["땀"], 							tags:["핑키빈콘"]},
	{name:"핑키빈물음표.png", 	keywords:["핑키빈?","핑키빈물음표"], 							tags:["핑키빈콘"]},
    {name:"뷰지.png", 	keywords:["뷰지"], 							tags:["핑키빈콘"]},
	{name:"비추.png", 	keywords:["비추"], 							tags:["핑키빈콘"]},
	{name:"뽀송.png", 	keywords:["뽀송"], 							tags:["핑키빈콘"]},
    {name:"XX귀.png", 	keywords:["뽀족귀"], 							tags:["핑키빈콘"]},
    {name:"핑키빈사망.png", 	keywords:["핑키빈사망"], 							tags:["핑키빈콘"]},
	{name:"싫름.png", 	keywords:["싫름"], 							tags:["핑키빈콘"]},
    {name:"야호.png", 	keywords:["야호"], 							tags:["핑키빈콘"]},
    {name:"어쩌라고.png", 	keywords:["어쩌라고"], 							tags:["핑키빈콘"]},
    {name:"운빨충.png", 	keywords:["운빨충"], 							tags:["핑키빈콘"]},
    {name:"응애.png", 	keywords:["응애"], 							tags:["핑키빈콘"]},
    {name:"잘가.png", 	keywords:["잘가"], 							tags:["핑키빈콘"]},
    {name:"저능아.png", 	keywords:["저능아"], 							tags:["핑키빈콘"]},
    {name:"적셔.png", 	keywords:["적셔"], 							tags:["핑키빈콘"]},
    {name:"질러.png", 	keywords:["질러"], 							tags:["핑키빈콘"]},
    {name:"코코낸내.png", 	keywords:["코코낸내"], 							tags:["핑키빈콘"]},
    {name:"크아악.png", 	keywords:["크아악"], 							tags:["핑키빈콘"]},
    {name:"틀.png", 	keywords:["틀"], 							tags:["핑키빈콘"]},
    {name:"푸하하.png", 	keywords:["푸하하"], 							tags:["핑키빈콘"]},
    {name:"핑키빈분노.png", 	keywords:["핑키빈분노"], 							tags:["핑키빈콘"]},
    {name:"한심.png", 	keywords:["한심"], 							tags:["핑키빈콘"]},
    {name:"해명해.png", 	keywords:["해명해"], 							tags:["핑키빈콘"]},
    {name:"호다닥.png", 	keywords:["호다닥"], 							tags:["핑키빈콘"]},
    {name:"홍.png", 	keywords:["홍"], 							tags:["핑키빈콘"]},
    {name:"힝힝.png", 	keywords:["힝힝"], 							tags:["핑키빈콘"]},
  
    {name:"노랑이댄스.gif", 	keywords:["노랑이댄스"], 							tags:["디시콘","어몽어스"]},
	{name:"주먹.gif", 	keywords:["주먹"], 							tags:["디시콘","어몽어스"]},
	{name:"소멸.gif", 	keywords:["소멸"], 							tags:["디시콘"]},
	{name:"엄.png", 	keywords:["엄"], 							tags:["디시콘"]},
	{name:"피.gif", 	keywords:["피"], 							tags:["디시콘"]},
	{name:"보리스.png", 	keywords:["보리스"], 							tags:["디시콘"]},
    {name:"어떤.png", 	keywords:["어떤"], 							tags:["디시콘"]},
	{name:"구울.png", 	keywords:["구울"], 							tags:["디시콘"]},
	{name:"대머리.gif", 	keywords:["대머리"], 							tags:["디시콘"]},
	{name:"머머리.gif", 	keywords:["머머리"], 							tags:["디시콘"]},
	{name:"스윗.gif", 	keywords:["스윗"], 							tags:["디시콘"]},
	{name:"무야호.gif", 	keywords:["무야호"], 							tags:["디시콘"]},

	
    {name:"꼴.png", 	keywords:["꼴"], 							tags:["둘리"]},
    {name:"ㅋㅋ또치.png", 	keywords:["ㅋㅋ또치"], 							tags:["둘리"]},
    {name:"밥줘.png", 	keywords:["밥줘"], 							tags:["둘리"]},
    {name:"선.png", 	keywords:["선"], 							tags:["둘리"]},
    {name:"아이.png", 	keywords:["아이"], 							tags:["둘리"]},
    {name:"처신.png", 	keywords:["처신"], 							tags:["둘리"]},
    {name:"초능력.png", 	keywords:["초능력"], 							tags:["둘리"]},
    {name:"어서오고.png", 	keywords:["어서오고"], 							tags:["둘리"]},
	
	{name:"강등.png", 	keywords:["강등"], 							tags:["띠껍티콘"]},
	{name:"경고1.png", 	keywords:["경고1"], 							tags:["띠껍티콘"]},
    {name:"경고2.png", 	keywords:["경고2"], 							tags:["띠껍티콘"]},
	{name:"고고.png", 	keywords:["고고"], 							tags:["띠껍티콘"]},
	{name:"노래.png", 	keywords:["노래"], 							tags:["띠껍티콘"]},
	{name:"돈1.png", 	keywords:["돈1"], 							tags:["띠껍티콘"]},
    {name:"돈2.png", 	keywords:["돈2"], 							tags:["띠껍티콘"]},
	{name:"돌.png", 	keywords:["돌"], 							tags:["띠껍티콘"]},
	{name:"라노벨.png", 	keywords:["라노벨"], 							tags:["띠껍티콘"]},
	{name:"선생님.png", 	keywords:["선생님"], 							tags:["띠껍티콘"]},
	{name:"설명.png", 	keywords:["설명"], 							tags:["띠껍티콘"]},
    {name:"승차.png", 	keywords:["승차"], 							tags:["띠껍티콘"]},
	{name:"어금니.png", 	keywords:["어금니"], 							tags:["띠껍티콘"]},
	{name:"예스.png", 	keywords:["예스"], 							tags:["띠껍티콘"]},
	{name:"와들.png", 	keywords:["와들"], 							tags:["띠껍티콘"]},
	{name:"풉.png", 	keywords:["풉"], 							tags:["띠껍티콘"]},
    {name:"띠껍하트.png", 	keywords:["띠껍하트"], 							tags:["띠껍티콘"]},
	{name:"행운.png", 	keywords:["행운"], 							tags:["띠껍티콘"]},
	{name:"흔들.png", 	keywords:["흔들"], 							tags:["띠껍티콘"]},
	{name:"힝.png", 	keywords:["힝"], 							tags:["띠껍티콘"]},
    {name:"깡통.png", 	keywords:["깡통"], 							tags:["띠껍티콘"]},
	
	{name:"조원희_.png", 	keywords:["조원희"], 							tags:["메이플"]}
	
];